### PR TITLE
Ability to specific device for playback in miniaudio

### PR DESCRIPTION
**Pull request by cameronmaske**
This is my first-pass adding in the ability to query for devices, and specific a `device_id` in the `PlaybackDevice` to control where playback occurs. 

```python
devices = miniaudio.Devices()
out_devices = devices.get_playbacks()

selected = out_devices[4]
print(device.name)
"Microphone (Yeti Stereo Microphone)"
print(device.info())
{'minChannels': 2, 'maxChannels': 2, 'minSampleRate': 48000, 'maxSampleRate': 48000}

in_devices = devices.get_captures()
# etc...
```

Opening this PR early to get any thoughts/feedback (especially around the API design).

### CODE REVIEW

**Comment by irmen** [comment]
This is great, thanks a lot.
I'll merge it and then have a look at the existing get_devices call, which should be changed into returning the new Device objects I think.

**Comment by cameronmaske** [comment]
Thanks for the prompt response @irmen.

A bit of context from my own testing is I kept `get_devices` as is, due to the behaviour of the [`finally: lib.ma_context_uninit(context)`](https://github.com/cameronmaske/synthesizer/blob/545e0f5bb984ce44b32b4344360ea23e36537e17/pyminiaudio/miniaudio.py#L748) which will de-referenced the device id pointer (which is totally reasonable in the course of the function, but will cause the device_id to not work as a reference). The whole idea behind the `Devices` class, is to keep the context around until the actual class is removed via the [`__del__`](https://github.com/cameronmaske/synthesizer/blob/545e0f5bb984ce44b32b4344360ea23e36537e17/pyminiaudio/miniaudio.py#L717) so the id pointers are still valid.

**Comment by irmen** [comment]
I've cleaned this up with 486436ac86e945aa234646902a614c94e525f567 and a774780e2e685950857407b38131512f4dbd78a5

**Comment by irmen** [comment]
@cameronmaske the device id being owned by the Devices class is tricky. It already caused a segfault in my code ;-)    
I've made it a private attribute on the DeviceInfo class now but ideally it should not depend on the lifecycle of the Devices class. Perhaps it's possible to copy it into a piece of memory owned by the DeviceInfo class.

Or better still; don't leak it out of the Devices class at all.  I think we should get all the devices info in one sweep in the get_playbacks()/get_captures() methods and just store the retrieved information in the DeviceInfo objects.

**Pull request merged**
